### ISSUE TITLE
amp-<test> when given invalid hostnames produces --help output

### ISSUE THREAD

**Issue by zafnz** [wandnz/amplet2#1]
When running a test on the commandline, eg amp-tcpping, and using an invalid/non-resolvable hostname, the output is just the --help, with no error message specified.

Actual Output:
```
root@tut5:~# amp-icmp -- google.not.a.domain
Usage: amp-icmp [-hrvx] [-p perturbate] [-s packetsize]
                [-Q codepoint] [-Z interpacketgap]
                [-I interface] [-4 sourcev4] [-6 sourcev6]
                -- destination1 [destination2 ... destinationN]

....... <snip>

```
Expected Output:
```
root@tut5:~# amp-icmp -- google.not.a.domain
WARNING google.not.a.domain does not resolve

```
(or similar)

**Comment by brendonj** [comment]
Tests will now warn if there were no valid destinations (rather than showing the usage statement), and standalone tests run on the command line will now warn for any individual destination that doesn't resolve to an address.

```
# amp-icmp -- google.not.a.domain
Tue Feb  7 10:19:14 2017 WARNING: Host 'google.not.a.domain' did not resolve!
Tue Feb  7 10:19:14 2017 WARNING: No resolvable destinations were specified!
```
