### ISSUE TITLE
Trying to compile the amplet2 on CentOS 7

### ISSUE THREAD

**Issue by kelvinyasu** [wandnz/amplet2#14]
Hello,

I am trying to compile the amplet2 on CentOS7 but it seem there is some error while compiling..
See if anyone got idea what's problem..

`*** Warning: Linking the executable amp-udpstream against the loadable module
*** udpstream.so is not portable!
make[6]: Leaving directory `/root/amplet2/src/tests/udpstream'
Making all in test
make[6]: Entering directory `/root/amplet2/src/tests/udpstream/test'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/root/amplet2/src/tests/udpstream/test'
make[5]: Leaving directory `/root/amplet2/src/tests/udpstream'
make[4]: Leaving directory `/root/amplet2/src/tests/udpstream'
make[3]: Leaving directory `/root/amplet2/src/tests'
Making all in measured
make[3]: Entering directory `/root/amplet2/src/measured'
Making all in .
make[4]: Entering directory `/root/amplet2/src/measured'
  CC       amplet2-run.o
  CC       amplet2-control.o
  CC       amplet2-messaging.o
messaging.c: In function ‚Äòconnect_to_broker‚Äô:
messaging.c:91:38: error: missing binary operator before token "("
 #if AMQP_VERSION >= AMQP_VERSION_CODE(0, 8, 0, 0)
                                      ^
messaging.c:107:25: error: ‚ÄòAMQP_SASL_METHOD_EXTERNAL‚Äô undeclared (first use in this function)
                         AMQP_SASL_METHOD_EXTERNAL, vars.ampname)
                         ^
messaging.c:107:25: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [amplet2-messaging.o] Error 1
make[4]: Leaving directory `/root/amplet2/src/measured'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/root/amplet2/src/measured'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/amplet2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/amplet2'
make: *** [all] Error 2`

**Comment by kelvinyasu** [comment]
I am trying to build the RPM too.. but where I can get the libwandevent-devel package? I did able to get libwandevent, but not libwandevent-devel...

Thank You..

**Comment by brendonj** [comment]
The build error is likely caused by not having librabbitmq-dev >= 0.7.1. Installing a version of librabbitmq-dev >= 0.7.1 should fix this error for you.

I've just tested with an older version of the library and it passes configure checks ok, but fails to build - I should tighten up the configure checks to ensure that it can't be built when the library is out of date.

**Comment by brendonj** [comment]
The libwandevent-devel package is built from [libwandevent](https://github.com/wanduow/libwandevent) but the CentOS spec file hasn't been added to that repository. I'll track it down and get it added so you can build your own RPM (we don't currently distribute it ourselves, though we may do so in the future).

**Comment by brendonj** [comment]
The [spec file](https://github.com/wanduow/libwandevent/blob/master/rpm/libwandevent.spec) for [libwandevent](https://github.com/wanduow/libwandevent) has been uploaded to the repository, which should allow you to build your own libwandevent and libwandevent-devel packages.
