### ISSUE TITLE
amp-http: HTTP header/Cache control header checks are case-sensitive

### ISSUE THREAD

**Issue by zafnz** [wandnz/amplet2#9]
Case control headers are ignored if not in the right case (eg X-Cache-Lookup, or Cache-Control), where the RFCs say these headers are case-sensitive.

Test case for this is annoying to produce, but it is obvious based on parsers.c that it is using strncmp and not strncasecmp.

Pull request coming shortly.

**Comment by zafnz** [comment]
This is fixed by the above pull request.

**Comment by brendonj** [comment]
Merged #10
